### ISSUE TITLE
[Minor] Search function

### ISSUE THREAD

**Issue by gcaelin30** [INFO442-Team2/Seattle-Sustenance#19]
First of all, dope AF project and the website works so well for the most part aside from minor things.

When you get on the landing page, it's nice and clear, however, when you go ahead and type in a zip code or search according to a specific criteria or criterion, there isn't a way to go back and tweak perhaps a criterion— instead you will have to go back to the main/home page in order to re-fill out the filter/search section in order to sort it out again and it doesn't save previous inputs.

It would be nice to have that feature, but of course with literally senioritis and a few days away til we graduate (YAYAYAYAY) no worries about it

**Comment by rachelvuu** [comment]
The defect will not be fixed before the deadline because a 'retry' button was not included in our requirements doc nor our wireframes. Additionally, users are able to click on the 'Find a Meal Program' link in the navigation bar to begin a new search.
