### ISSUE TITLE
Retrying Form

### ISSUE THREAD

**Issue by kevin-chiu** [INFO442-Team2/Seattle-Sustenance#20]
Describe the bug
I could not redo the form after a result has been found. This is inconsistent with allowing the user to refine search results if a program could not be found.
 
To Reproduce

Enter a valid zip code (98115) and click go
A valid result will show with no button to retry

Expected behavior
I expected a button or a link to be able to retry the form if I wanted to view more search results that pertained to different zip codes

Screenshots
This screenshot shows how it allows users to retry search results that are invalid
![image](https://user-images.githubusercontent.com/31137647/83925751-cf899c80-a73c-11ea-945b-e28afb2ac89b.png)

This screenshot does not allow to resubmit another form
![image](https://user-images.githubusercontent.com/31137647/83925830-fa73f080-a73c-11ea-8ce2-952bfaa73586.png)

**Comment by rachelvuu** [comment]
Marking as duplicate with issue #19 — also, when no results are found, the user remains on the search page and doesn't need a button to retry.
